// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-bhmO2evjrfxSR6FIfiwIvDlJaM5wNTQ',
    appId: '1:675705772951:web:3f1006019bad1a989f02d2',
    messagingSenderId: '675705772951',
    projectId: 'the-date-deck-5bd88',
    authDomain: 'the-date-deck-5bd88.firebaseapp.com',
    databaseURL: 'https://the-date-deck-5bd88-default-rtdb.firebaseio.com',
    storageBucket: 'the-date-deck-5bd88.firebasestorage.app',
    measurementId: 'G-38VY2SC8F0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBtat9MVqWoYpjFMSaGNvNqmiriRiLjIU',
    appId: '1:675705772951:android:d3fce56b06d939109f02d2',
    messagingSenderId: '675705772951',
    projectId: 'the-date-deck-5bd88',
    databaseURL: 'https://the-date-deck-5bd88-default-rtdb.firebaseio.com',
    storageBucket: 'the-date-deck-5bd88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcKfUg51TlnxrhCSuhxFdPiHiElcRtOGE',
    appId: '1:675705772951:ios:1b8ff1bfee00d0429f02d2',
    messagingSenderId: '675705772951',
    projectId: 'the-date-deck-5bd88',
    databaseURL: 'https://the-date-deck-5bd88-default-rtdb.firebaseio.com',
    storageBucket: 'the-date-deck-5bd88.firebasestorage.app',
    iosClientId: '675705772951-gi67vs09o04210hghel8v0l73s5vjukj.apps.googleusercontent.com',
    iosBundleId: 'com.TopazSkyline.dateDeck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcKfUg51TlnxrhCSuhxFdPiHiElcRtOGE',
    appId: '1:675705772951:ios:1b8ff1bfee00d0429f02d2',
    messagingSenderId: '675705772951',
    projectId: 'the-date-deck-5bd88',
    databaseURL: 'https://the-date-deck-5bd88-default-rtdb.firebaseio.com',
    storageBucket: 'the-date-deck-5bd88.firebasestorage.app',
    iosClientId: '675705772951-gi67vs09o04210hghel8v0l73s5vjukj.apps.googleusercontent.com',
    iosBundleId: 'com.TopazSkyline.dateDeck',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-bhmO2evjrfxSR6FIfiwIvDlJaM5wNTQ',
    appId: '1:675705772951:web:b8d3b12c8fb60a409f02d2',
    messagingSenderId: '675705772951',
    projectId: 'the-date-deck-5bd88',
    authDomain: 'the-date-deck-5bd88.firebaseapp.com',
    databaseURL: 'https://the-date-deck-5bd88-default-rtdb.firebaseio.com',
    storageBucket: 'the-date-deck-5bd88.firebasestorage.app',
    measurementId: 'G-KZ0NP8JV46',
  );

}